SECTORS = {
    "Todos": "",
    "Bens Industriais": "70",
    "Consumo Cíclico": "36",
    "Consumo Não Cíclico": "20",
    "Consumo Não Cíclico": "20",
    "Financeiro": "95",
    "Materias Básicos": "1",
    "Petróleo, Gás e Combustíveis": "115",
    "Saúde": "126",
    "Tecnologia da Informação": "138",
    "Telecomunicações": "135",
    "Utilidade Pública": "119"
}


QUANTIDADE = "1000"
FILTROS2 = {
    "setor": SECTORS["Financeiro"],
    "p_l_min": "0",
    "p_l_max": "15",
    "p_vp_min": "0",
    "p_vp_max": "1.5",
    "dy_min": "2",
    "dy_max": "25",
}

FILTROS = {
    "setor": SECTORS["Todos"],
    "p_l_min": "0",
    "p_l_max": "100",
    "p_vp_min": "0",
    "p_vp_max": "100",
    "dy_min": "0",
    "dy_max": "100",
}

headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
}

body = {
    "start": "0",
    "length": QUANTIDADE,
    # "search[value]": "",
    # "search[regex]": "false",
    "sector": FILTROS['setor'],
    # "subsector": "",
    "segment": "Todos",
    "ranges[p_l][0]": FILTROS['p_l_min'],
    "ranges[p_l][1]": FILTROS['p_l_max'],
    "ranges[p_l][2]": "true",
    "ranges[p_l][3]": "true",
    "ranges[p_vp][0]": FILTROS['p_vp_min'],
    "ranges[p_vp][1]": FILTROS['p_vp_max'],
    "ranges[p_vp][2]": "true",
    "ranges[p_vp][3]": "true",
    "ranges[dividend_yield_last_12_months][0]": FILTROS['dy_min'],
    "ranges[dividend_yield_last_12_months][1]": FILTROS['dy_max'],
    "ranges[dividend_yield_last_12_months][2]": "true",
    "ranges[dividend_yield_last_12_months][3]": "true",
    "ranges[net_margin][0]": "0",
    "ranges[net_margin][1]": "100",
    "ranges[net_margin][2]": "false",
    "ranges[net_margin][3]": "false",
    "ranges[gross_margin][0]": "0",
    "ranges[gross_margin][1]": "100",
    "ranges[gross_margin][2]": "false",
    "ranges[gross_margin][3]": "false",
    "ranges[ebit_margin][0]": "0",
    "ranges[ebit_margin][1]": "100",
    "ranges[ebit_margin][2]": "false",
    "ranges[ebit_margin][3]": "false",
    "ranges[ev_ebit][0]": "0",
    "ranges[ev_ebit][1]": "100",
    "ranges[ev_ebit][2]": "false",
    "ranges[ev_ebit][3]": "false",
    "ranges[p_ebit][0]": "0",
    "ranges[p_ebit][1]": "100",
    "ranges[p_ebit][2]": "false",
    "ranges[p_ebit][3]": "false",
    "ranges[p_assets][0]": "0",
    "ranges[p_assets][1]": "100",
    "ranges[p_assets][2]": "false",
    "ranges[p_assets][3]": "false",
    "ranges[p_working_capital][0]": "0",
    "ranges[p_working_capital][1]": "100",
    "ranges[p_working_capital][2]": "false",
    "ranges[p_working_capital][3]": "false",
    "ranges[psr][0]": "0",
    "ranges[psr][1]": "100",
    "ranges[psr][2]": "false",
    "ranges[psr][3]": "false",
    "ranges[vpa][0]": "0",
    "ranges[vpa][1]": "100",
    "ranges[vpa][2]": "false",
    "ranges[vpa][3]": "true",
    "ranges[lpa][0]": "0",
    "ranges[lpa][1]": "100",
    "ranges[lpa][2]": "false",
    "ranges[lpa][3]": "true",
    "ranges[active_turns][0]": "0",
    "ranges[active_turns][1]": "100",
    "ranges[active_turns][2]": "false",
    "ranges[active_turns][3]": "false",
    "ranges[roe][0]": "0",
    "ranges[roe][1]": "100",
    "ranges[roe][2]": "true",
    "ranges[roe][3]": "true",
    "ranges[roic][0]": "0",
    "ranges[roic][1]": "100",
    "ranges[roic][2]": "false",
    "ranges[roic][3]": "false",
    "ranges[roa][0]": "0",
    "ranges[roa][1]": "100",
    "ranges[roa][2]": "false",
    "ranges[roa][3]": "false",
    "ranges[net_debt_net_worth][0]": "0",
    "ranges[net_debt_net_worth][1]": "20",
    "ranges[net_debt_net_worth][2]": "false",
    "ranges[net_debt_net_worth][3]": "false",
    "ranges[net_debt_ebit][0]": "0",
    "ranges[net_debt_ebit][1]": "20",
    "ranges[net_debt_ebit][2]": "false",
    "ranges[net_debt_ebit][3]": "false",
    "ranges[net_worth_assets][0]": "0",
    "ranges[net_worth_assets][1]": "5",
    "ranges[net_worth_assets][2]": "false",
    "ranges[net_worth_assets][3]": "false",
    "ranges[liabilities_assets][0]": "0",
    "ranges[liabilities_assets][1]": "5",
    "ranges[liabilities_assets][2]": "false",
    "ranges[liabilities_assets][3]": "false",
    "ranges[current_liquidity][0]": "0",
    "ranges[current_liquidity][1]": "20",
    "ranges[current_liquidity][2]": "false",
    "ranges[current_liquidity][3]": "false",
    "ranges[growth_net_revenue_last_5_years][0]": "0",
    "ranges[growth_net_revenue_last_5_years][1]": "100",
    "ranges[growth_net_revenue_last_5_years][2]": "false",
    "ranges[growth_net_revenue_last_5_years][3]": "false",
    "ranges[growth_net_profit_last_5_years][0]": "0",
    "ranges[growth_net_profit_last_5_years][1]": "100",
    "ranges[growth_net_profit_last_5_years][2]": "false",
    "ranges[growth_net_profit_last_5_years][3]": "false",
    "ranges[dividend_yield_last_5_years][0]": "0",
    "ranges[dividend_yield_last_5_years][1]": "100",
    "ranges[dividend_yield_last_5_years][2]": "false",
    "ranges[dividend_yield_last_5_years][3]": "false"
}
